package io.github.qishr.cascara.lang.yaml.ast;

import java.net.URI;
import java.util.List;
import java.util.Objects;
import io.github.qishr.cascara.common.lang.ast.QuoteStyle;
import io.github.qishr.cascara.common.lang.ast.ScalarAstNode;

/// Represents a leaf node in the YAML AST containing a single scalar value.
public class YamlScalarNode extends YamlNode implements ScalarAstNode<YamlNode> {
    private String value;
    private String rawValue;
    // private final String value;
    private QuoteStyle quoteStyle;

    public YamlScalarNode(int line, int column, URI uri, String rawValue, String stringValue, QuoteStyle quoteStyle) {
        super(line, column, uri);
        this.rawValue = rawValue;
        this.value = stringValue;
        this.quoteStyle = quoteStyle;
    }

    /// Convenience constructor for Serializer use (programmatic creation).
    ///
    /// @param value The logical value.
    /// @param style The desired quoting style.
    public YamlScalarNode(String value, QuoteStyle style) {
        super(0, 0, null);
        this.value = value;
        this.quoteStyle = style;
        this.rawValue = null; // Will be generated by the Emitter based on style
    }

    public YamlScalarNode() {
        super(0, 0, null);
        this.quoteStyle = QuoteStyle.PLAIN;
        this.rawValue = null;
    }

    /// {@inheritDoc}
    @Override
    public String getString() {
        return value;
    }

    /// {@inheritDoc}
    @Override
    public String toString() {
        return value;
    }

    /// {@inheritDoc}
    @Override
    public int getInteger() {
        return getInteger(0);
    }

    /// {@inheritDoc}
    @Override
    public int getInteger(int defaultValue) {
        try {
            return value == null ? defaultValue : Integer.parseInt(value);
        } catch (NumberFormatException e) {
            return defaultValue;
        }
    }

    /// {@inheritDoc}
    @Override
    public double getDouble() {
        return getDouble(0.0);
    }

    /// {@inheritDoc}
    @Override
    public double getDouble(double defaultValue) {
        try {
            return value == null ? defaultValue : Double.parseDouble(value);
        } catch (NumberFormatException e) {
            return defaultValue;
        }
    }

    /// {@inheritDoc}
    @Override
    public boolean getBoolean() {
        return Boolean.parseBoolean(value);
    }

    /// {@inheritDoc}
    @Override
    public boolean getBoolean(boolean defaultValue) {
        // TODOL This needs to behave like the other getters with default values
        return Boolean.parseBoolean(value);
    }

    /// {@inheritDoc}
    /// Performs basic type inference to return the most appropriate Java object.
    @Override
    public Object getPrimitiveValue() {
        if (value == null) return null;
        if (isQuoted()) return value; // Quoted values are always strings

        // Boolean check
        if (value.equalsIgnoreCase("true") || value.equalsIgnoreCase("yes")) return Boolean.TRUE;
        if (value.equalsIgnoreCase("false") || value.equalsIgnoreCase("no")) return Boolean.FALSE;

        // Integer check
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            // Not an integer, move on
        }

        // Double check
        try {
            return Double.parseDouble(value);
        } catch (NumberFormatException e) {
            // Not a double, move on
        }

        return value;
    }

    @Override
    public void setPrimitiveValue(Object value) {
        this.value = String.valueOf(value);
    }

    /// Returns the original raw (unescaped) string as seen in the source file.
    public String getRawValue() {
        return (rawValue != null) ? rawValue : value;
    }

    /// Gets the quoting style used for this scalar.
    public QuoteStyle getQuoteStyle() {
        return quoteStyle;
    }

    /// {@inheritDoc}
    /// Scalars are leaf nodes and have no children.
    @Override
    public List<YamlNode> getChildren() {
        return List.of();
    }

    // @Override
    public String getValue() {
        return value;
    }

    /// Compares this scalar with another for equality.
    ///
    /// Two scalars are considered equal if they share the same anchor
    /// and logical string value. Source coordinates and quoting styles
    /// are ignored.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof YamlScalarNode that)) return false;
        return Objects.equals(value, that.value);
    }

    /// {@inheritDoc}
    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    // Updated getter to derive from style
    public boolean isQuoted() {
        return quoteStyle != QuoteStyle.PLAIN;
    }

    @Override
    public void setValue(String newValue) {
        this.value = newValue;
        this.rawValue = null; // Mark as "dirty" / programmatically changed
    }

    /// Sets the quoting style and clears the raw cache.
    public void setQuoteStyle(QuoteStyle quoteStyle) {
        this.quoteStyle = quoteStyle;
        this.rawValue = null;
    }
}